# src/runtime/token_types.py

SKIP  = "skip"
EOL   = "EOL"
PLUS  = "PLUS"
MINUS = "MINUS"
TIMES = "TIMES"
LPAREN= "LPAREN"
RPAREN= "RPAREN"
EOF   = "EOF"
WORD  = "WORD"
LETTER= "LETTER"
NUMBER= "NUMBER"
ID        = "ID"
SEMICOLON = "SEMICOLON"
ASSIGNOP  = "ASSIGNOP"
LT        = "LT"
EQ        = "EQ"